// Why can participant 0 not pay a fee?
//
// Fees on Midnight are paid in dust, dust is generated by registered NIGHT, and
// it accrues over time rather than arriving. Three separate things can be wrong
// and the error message ("could not balance dust") does not say which:
//   1. no NIGHT at all
//   2. NIGHT held but never registered for dust generation
//   3. registered, but not enough dust has accrued yet
//
// So measure all three instead of guessing.

import "./midnight-target.ts";
import "@midnight-ntwrk/onchain-runtime-v3";

import {
  buildWalletFacade,
  resolveFacadeDustBalance,
  midnightNetworkConfig,
} from "@effectstream/midnight-contracts";
import * as Rx from "rxjs";
import { allSeeds, readLocalEnv } from "./participants.ts";

const mnemonic = readLocalEnv("MIDNIGHT_WALLET_MNEMONIC");
if (!mnemonic) {
  console.error("no mnemonic");
  process.exit(1);
}

const which = Number(process.argv[2] ?? "0");
const networkId = (process.env.MIDNIGHT_NETWORK_ID ?? "preprod") as never;
const net = midnightNetworkConfig;
const urls = {
  id: net.id, indexer: net.indexer, indexerWS: net.indexerWS,
  node: net.node, proofServer: net.proofServer,
};

const w = await buildWalletFacade(urls as never, allSeeds(mnemonic)[which], networkId);
console.log(`participant ${which}`);
console.log(`  night: ${w.unshieldedAddress}`);
console.log(`  dust:  ${w.dustAddress}`);
console.log("");

const settle = Number(process.env.DARKMARKET_SETTLE_MS ?? 90000);
console.log(`letting streams run for ${settle / 1000}s, then reading state...`);
await new Promise((r) => setTimeout(r, settle));

const state: Record<string, unknown> = await Rx.firstValueFrom(
  (w.wallet as unknown as { state: () => Rx.Observable<Record<string, unknown>> }).state(),
);

const unshielded = state.unshielded as
  | { availableCoins?: { meta?: { registeredForDustGeneration?: boolean }; utxo?: { value?: bigint } }[] }
  | undefined;
const coins = unshielded?.availableCoins ?? [];
const registered = coins.filter((c) => c.meta?.registeredForDustGeneration === true);

console.log("");
console.log(`NIGHT utxos:            ${coins.length}`);
console.log(`  registered for dust:  ${registered.length}`);
console.log(`  unregistered:         ${coins.length - registered.length}`);
for (const c of coins.slice(0, 6)) {
  console.log(`    value=${c.utxo?.value ?? "?"} registered=${c.meta?.registeredForDustGeneration}`);
}

try {
  const dust = await resolveFacadeDustBalance(w.wallet as never);
  console.log("");
  console.log(`dust balance: ${dust}`);
  console.log(dust && BigInt(String(dust)) > 0n
    ? "there is dust: the failure is about amount, not registration"
    : "no dust at all: either nothing is registered, or none has accrued yet");
} catch (e: unknown) {
  console.log("dust balance read failed:", String((e as Error)?.message ?? e).slice(0, 140));
}

process.exit(0);
